import React, { useEffect, useState } from 'react'
import Head from "next/head";
import styled from "styled-components"
import { Sidebar, Chat, } from "../components"

export default function Home() {
  const [chat, setChat] = useState(null)

  return (
    <div>
      <Head>
        <title>WhatsApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Content>
          <Sidebar currentChat={chat} setCurrentChat={(c) => setChat(c)} />
          {
            chat === null
              ? <Blank>
                <h1>Click on a chat...</h1>
              </Blank>
              : <Chat currentChat={chat} />
          }
        </Content>
      </Container>
    </div>
  )
}

const Container = styled.div`
	margin: 0 auto;
	width: 1400px;
	display: grid;
	height: 100vh;
`

const Content = styled.div`
	background-color: #262d31;
	box-shadow: 0px 0px 10px 1px #0b0e11;
	margin-top: 25px;
	margin-bottom: 25px;
	display: flex;
`

const Blank = styled.div`
	display: flex;
	flex: 1;
	flex-direction: column;
	justify-content: center;
	align-items: center;
	color: white;
`

