import Head from 'next/head'
import styled from 'styled-components'
import Sidebar from '../components/Sidebar.js'

export default function Home() {
  return (
    <div>
      <Head>
        <title>WhatsApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Content>
          <Sidebar />
          <Chat>
            Hi
          </Chat>
        </Content>
      </Container>
    </div>
  )
}

const Container = styled.div`
  margin: 0 auto;
  width: 1400px;
  display: grid;
  height: 100vh;
`

const Content = styled.div`
  background-color: #262D31;
  box-shadow: 0px 0px 10px 1px #0B0E11;
  margin-top: 25px;
  margin-bottom: 25px;
  display: flex;
`

const Chat = styled.div`
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
`
