import {
	appReducer,
	setMicOn,
	setMicOff,
	setCurrentPage,
	isMicOn,
	getCurrentPage,
	authReducer,
	setCurrentUser,
	nullCurrentUser,
	getCurrentUser,
	serversReducer,
	addServer,
	updateServer,
	removeServer,
	clearServers,
	setCurrentServer,
	addChannel,
	updateChannel,
	removeChannel,
	clearChannels,
	setCurrentChannel,
	getServers,
	getChannels,
	getCurrentServer,
	getCurrentChannel,
} from './reducers'

import store from './store'

export {
	appReducer,
	setMicOn,
	setMicOff,
	setCurrentPage,
	isMicOn,
	getCurrentPage,
	authReducer,
	setCurrentUser,
	nullCurrentUser,
	getCurrentUser,
	serversReducer,
	addServer,
	updateServer,
	removeServer,
	clearServers,
	setCurrentServer,
	addChannel,
	updateChannel,
	removeChannel,
	clearChannels,
	setCurrentChannel,
	getServers,
	getChannels,
	getCurrentServer,
	getCurrentChannel,
	store,
}
